{
 "title": "CCX Internal Data Pipeline",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   },
   {
    "name": "services",
    "label": "services",
    "query": "multiplexor,archive-sync,archive-sync-ols,rules-processing,rules-uploader,"
   },
   { "name": "parquet_factory_datasource", "label": "PF datasource", "query": "prometheus" },
   {
    "name": "parquet_factory_namespace",
    "label": "PF namespace",
    "query": "app-sre-observability-stage,app-sre-observability-production"
   }
  ]
 },
 "panels": [
  {
   "title": "Total received",
   "type": "timeseries",
   "description": "The amount of files received by each service should be the same",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\", pod=~\"$services.*\"}[1m])) by(service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Parquet Factory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "offset_marked{job=\"parquet-factory\", namespace=\"$parquet_factory_namespace\"}",
     "legendFormat": "Marked"
    },
    {
     "expr": "offset_consummed{job=\"parquet-factory\", namespace=\"$parquet_factory_namespace\"}",
     "legendFormat": "Consumed"
    },
    {
     "expr": "offset_processed{job=\"parquet-factory\", namespace=\"$parquet_factory_namespace\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "rate(inserted_rows{job=\"parquet-factory\", namespace=\"$parquet_factory_namespace\"}[5m])",
     "legendFormat": "Inserted"
    }
   ]
  },
  { "title": "$services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "services" },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(ccx_consumer_received_total{namespace=\"$namespace\", service=~\"$services.*\"}[1m])) by(service)",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(ccx_engine_processed_total{namespace=\"$namespace\", service=~\"$services.*\"}[1m])) by(service)",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(rate(ccx_published_total{namespace=\"$namespace\", service=~\"$services.*\"}[1m])) by(service)",
     "legendFormat": "Published"
    },
    {
     "expr": "sum(rate(ccx_not_handled_total{namespace=\"$namespace\", service=~\"$services.*\"}[1m])) by(service)",
     "legendFormat": "Not handled"
    },
    {
     "expr": "sum(rate(ccx_failures_total{namespace=\"$namespace\", service=~\"$services.*\"}[1m])) by(service)",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Maximum CPU usage across all pods (% of limit)",
   "type": "timeseries",
   "description": "Use this panel to look for anomalies. Spikes are expected. The usage should never reach 1.\nFeel free to enter this panel and enable the hidden metrics which will give you a better view on the individual pods.",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(sum(rate(process_cpu_seconds_total{namespace=\"$namespace\", service=~\"$services.*\"}[1m])) by(pod) / sum(kube_pod_resource_limit{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$services.*\"}) by(pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum RAM usage across all pods (% of limit)",
   "type": "timeseries",
   "description": "Use this panel to look for anomalies. Spikes are expected. The usage should never reach 1.\nFeel free to enter this panel and enable the hidden metrics which will give you a better view on the individual pods.",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(sum(process_resident_memory_bytes{namespace=\"$namespace\", service=~\"$services.*\"}) by(pod) / sum(kube_pod_resource_limit{namespace=\"$namespace\", resource=\"memory\", pod=~\"$services.*\"}) by(pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", service=~\"$services.*\"}) by(service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}