name: Pytest

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.10
    container: python:${{ python-version }}-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          pip install --upgrade setuptools
          pip install --upgrade wheel
          pip install pycodestyle
          pip install pydocstyle
          pip install pytest-cov
          pip install --upgrade importlib-metadata
          pip install -r requirements.txt
          pip install -e .[dev] || pip install -e .
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov

      - name: Pytest Coverage
        run: |
          pytest -v --cov=ccx_messaging --cov-fail-under=70
          pytest -v --cov=ccx_messaging --cov-report=xml
          ./codecov -t c5c72a0d-fa95-4f38-8015-9aadbaf46466
