name: Tests

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade setuptools
      - run: pip install --upgrade wheel
      - run: pip install tox-gh>=1.2
      - run: tox -vv
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: ${{ matrix.python-version == '3.11' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
